//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AttackWeakestStrategy.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class AttackWeakestStrategy extends Strategy {
    Team enemyTeam;
    float rangedAttackProb = 0.01f;
    Knight target = null;
    public AttackWeakestStrategy(Knight owner) {
        super(owner);
        enemyTeam = owner.getTeam().enemy;
        target = enemyTeam.get(0);
        getWeakest();
        
    }

    @Override
    public void act() {
        getWeakest();
        owner.moveTo( target.getX(), target.getY());
        if (rangedAttackProb > rng.nextDouble())
            owner.rangedAttack();
    }
    
    public void getWeakest () {
        if (target == null)
            target = enemyTeam.get(0);
        for (int i = 0; i<enemyTeam.size(); i++ )
            if (enemyTeam.get(i)!=null || target.getHP() > enemyTeam.get(i).getHP()) {
                target = enemyTeam.get(i);
            }
    }
    
}
