
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Display.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//


public class Display extends JPanel{
    Image map;
    Image logo;
	public Display() {
            super();
            this.setBorder(new LineBorder(Color.BLACK));
            this.getBorder().isBorderOpaque();
        try {
            map = ImageIO.read(new File("map.png"));
            logo = ImageIO.read(new File("logo.png"));
        } catch (IOException ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }
	}
	
    @Override
	public Dimension getPreferredSize() {
            return new Dimension (800, 600);
	}
	
    @Override
	public void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;
            g2d.drawImage(map, 240, -50, null);
            g2d.drawImage(logo, -20, 300, null);
            for (int i = 0; i<Simulation.TEAM_SIZE;i++){
                if (Simulation.Instance().teams[0].get(i)!= null)
                    Simulation.Instance().teams[0].get(i).draw(g2d);
                if (Simulation.Instance().teams[1].get(i)!= null)
                    Simulation.Instance().teams[1].get(i).draw(g2d);
            }
            g2d.drawString("El Morad          Karus", 80, 20);
            g2d.drawString("Score:               " + Simulation.Instance().teams[0].score + "                       " + Simulation.Instance().teams[1].score, 15, 40);
            g2d.drawString("Kills:                 " + Simulation.Instance().teams[0].score / 75 + "                       " + Simulation.Instance().teams[1].score/75, 15, 60);
            g2d.drawString("T. Damage:     " + Simulation.Instance().teams[0].totalDamage + "                       " + Simulation.Instance().teams[1].totalDamage, 15, 80);
            
            
	}
        
        
        
}
