//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SoldierFactory.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public abstract class KnightFactory {
    
    public abstract Knight produce();
}
