//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MageFactory.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class MageFactory extends KnightFactory {

    @Override
    
    public Knight produce() {
        return new Mage();
    }
}
