//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PriestFactory.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class PriestFactory extends KnightFactory {

    @Override
    public Knight produce() {
        return new Priest();
    }
}
