//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RandomMovementStrategy.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class RandomMovementStrategy extends Strategy {
    float targetx, targety;
    public RandomMovementStrategy(Knight owner) {
        super(owner);
        chooseRandomSpot();
    }

    @Override
    public void act() {
        if (Math.abs(targetx - owner.getX()) < 50|| Math.abs(targety - owner.getY()) < 50)
            chooseRandomSpot();
        owner.moveTo(targetx, targety);
    }
    private void chooseRandomSpot (){
        targetx =300 + rng.nextInt(Simulation.Instance().getWidth()-325);
        targety = 25 + rng.nextInt(Simulation.Instance().getHeight()-25);
    }
}
