
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.util.Timer;
import java.util.TimerTask;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rogue.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class Rogue extends Knight {

    Polygon poly = new Polygon(
                    new int[]{0, 10, -10},
                    new int[]{-10, 10, 10},
                3);
    
    @Override
    public void rangedAttack() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void draw(Graphics2D g) {
        Graphics2D gc = (Graphics2D) g.create();
        gc.setColor(getTeam().color);
        gc.translate(getX(), getY());
        gc.fill(poly);
        if (this.isAttacking()) {
            gc.setColor(Color.YELLOW);
             gc.drawLine(0,0, (int) (getAttackTarget().getX() - getX()), (int) ((int)getAttackTarget().getY() - getY()));
        }
        gc.setColor(Color.WHITE);
        gc.setFont(Font.decode("arial 10"));
        gc.drawString("" + this.getHP(), -8, 5);
        gc.dispose();
    }
    Rogue () {
        speed = 100;
        canAttack = true;
        coolDown = new Timer();
        hitPoint = 500;
        score = 0;
        pxToMove = speed / (1000f / Simulation.DELAY);
        maxHealth = 500;
        cdLength = 1000;
        attackRadius = 35;
    }
    
}
