//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RogueFactory.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class RogueFactory extends KnightFactory {

    @Override
    public Knight produce() {
        return new Rogue();
    }
    
}
