
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Strategy.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public abstract class Strategy {
	public Knight owner;
        public boolean finished;
        Random rng;
	public abstract void act() ;
        
        Strategy (Knight owner) {
            this.owner = owner;
            rng = new Random();
        }
}
