
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Team.java
//  @ Date : 13.3.2015
//  @ Author : 
//
//




public class Team {
        public int totalDamage;
        public int spawnX, spawnY;
        public Random rng;
	public int score;
	public Color color;
	public ArrayList <Knight> knights;
        public String name;
        public int teamSize;
        public Team enemy;
        
        Team (Color c, String name, int teamSize, int x, int y) {
            rng = new Random(); 
            score = 0;
            color = c;
            knights = new ArrayList <>();
            this.teamSize = teamSize;
            spawnX = x;
            spawnY = y;
        };
        
        void addKnight (Knight k){
            if (knights.size() < teamSize) {
               k.setX(spawnX -50 + rng.nextInt(100));
               k.setY(spawnY -50 + rng.nextInt(100));
               k.setTeam(this);
               knights.add(k);
            }
        }
        
        void removeKnight (Knight k) {

            Timer t = new Timer();
            t.schedule(new TimerTask() {

                @Override
                public void run() {
                    if (knights.contains(k))
                        knights.remove(k);
                }
            },20);
        }
        int getScore (){
            return score;
        }
        void setScore (int s) {
            score+=s;
        }
        Knight get (int i) {
            if (i < knights.size())
                return knights.get(i);
            return null;
        }

    boolean isFull() {
        return knights.size() >= teamSize; 
    }

    int size() {
        return knights.size();
    }
    
    void set(int i, Knight k) {
        knights.set(i, k);
    }
    
}
